language: R
cache: packages

r_packages:
  - covr

r_github_packages:
  - tidyverse/lubridate

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email: false
  slack:
    rooms:
      - poissonconsulting:BKjfn7jsVh8zXTu2rq7BEQEb
    on_success: change
    on_failure: always

