#' Analyse Models
#'
#' @description
#' Fit a Bayesian hierarchical model to data using Stan (via rstan or cmdstanr)
#' or JAGS (via rjags). The estimation backend is determined by the model
#' class (JAGS or Stan) and, for Stan models, by the `stan_engine` argument.
#'
#' @details
#' For Stan models using a `cmdstan-*` engine, embr sets a fixed set of
#' cmdstanr arguments from its own parameters (listed in each engine section).
#' These cannot be overridden via `...` and are dropped with a warning if
#' passed. Other cmdstanr arguments pass through `...`.
#'
#' `init` is the sole exception: it can be overridden via `...`, replacing
#' inits generated by `gen_inits()` in [model()]. Non-MCMC engines do not use
#' `gen_inits()`.
#'
#' `nthin` and `niters_warmup` are ignored by non-MCMC engines. For
#' pathfinder, variational, and laplace, `niters` sets the number of draws
#' from the approximated posterior.
#'
#' @section cmdstan-mcmc:
#'   Calls [cmdstanr::sample()].
#'
#'   embr-controlled: `chains`, `parallel_chains`, `iter_warmup`,
#'   `iter_sampling`, `thin`, `data`, `seed`, `init`, `show_messages`,
#'   `show_exceptions`.
#'
#'   Common pass-throughs: `adapt_delta`, `max_treedepth`, `step_size`,
#'   `refresh`, `output_dir`, `save_warmup`.
#'
#' @section cmdstan-pathfinder:
#'   Calls [cmdstanr::pathfinder()].
#'
#'   embr-controlled: `data`, `seed`, `init`, `draws` (from `niters`),
#'   `show_messages`, `show_exceptions`.
#'
#'   Common pass-throughs: `num_paths`, `history_size`, `max_lbfgs_iters`,
#'   `psis_resample`, `tol_rel_grad`.
#'
#' @section cmdstan-variational:
#'   Calls [cmdstanr::variational()].
#'
#'   embr-controlled: `data`, `seed`, `init`, `draws` (from `niters`),
#'   `show_messages`, `show_exceptions`.
#'
#'   Common pass-throughs: `algorithm` (`"meanfield"` or `"fullrank"`), `iter`,
#'   `tol_rel_obj`, `eval_elbo`, `eta`.
#'
#' @section cmdstan-optimize:
#'   Calls [cmdstanr::optimize()].
#'
#'   embr-controlled: `data`, `seed`, `init`, `show_messages`,
#'   `show_exceptions`.
#'
#'   Common pass-throughs: `algorithm` (`"lbfgs"`, `"bfgs"`, or `"newton"`),
#'   `iter`, `tol_obj`, `history_size`, `jacobian`.
#'
#' @section cmdstan-laplace:
#'   Calls [cmdstanr::laplace()].
#'
#'   embr-controlled: `data`, `seed`, `init`, `mode`, `draws` (from `niters`),
#'   `show_messages`, `show_exceptions`.
#'
#'   Common pass-throughs: `jacobian`, `opt_args`.
#'
#' @section rstan:
#'   For Stan models without a `stan_engine` matching one of the cmdstan
#'   options above, [rstan::sampling()] is called. Pass its arguments through
#'   `...`; for example, `control = list(adapt_delta = 0.95)`.
#'
#' @param x An `mb_model` object.
#' @param data A data frame, or a named list of data frames for meta-analysis
#'   across datasets.
#' @inheritParams params
#' @param ... Additional arguments passed to the underlying estimation
#'   function.
#' @return
#' An `mb_analysis` if `data` is a single data frame, or an
#' `mb_meta_analysis` if `data` is a named list of data frames.
#'
#' @seealso
#' * The [analyse article](https://poissonconsulting.github.io/embr/articles/analyse.html)
#'   for a walkthrough of the fitting workflow.
#' * [model()] to build a model.
#' * [set_analysis_mode()] to set session-wide sampling defaults.
#' * [analyse.mb_models()] to fit a list of models simultaneously.
#' * [analyse.character()] to fit from raw model code.
#' * [predict.mb_analysis()] and [coef.mb_analysis()] to summarise an
#'   analysis.
#' * [reanalyse()] to refit with different sampling settings.
#'
#' @examples
#' \dontrun{
#' # Stan model with cmdstanr MCMC
#' analysis <- analyse(stan_model, data,
#'   stan_engine = "cmdstan-mcmc",
#'   nchains = 4, niters = 1000
#' )
#'
#' # JAGS model
#' analysis <- analyse(jags_model, data, nchains = 4, niters = 2000)
#'
#' # Engine-specific argument via ...
#' analysis <- analyse(stan_model, data,
#'   stan_engine = "cmdstan-mcmc",
#'   adapt_delta = 0.99
#' )
#'
#' # Override initial values for cmdstanr MCMC
#' init_fun <- function() list(bIntercept = 0)
#' analysis <- analyse(stan_model, data,
#'   stan_engine = "cmdstan-mcmc",
#'   init = init_fun
#' )
#'
#' # Multiple datasets
#' analyses <- analyse(model, list(dataset1 = data1, dataset2 = data2))
#' }
#'
#' @export
analyse <- function(x, ...) {
  UseMethod("analyse")
}

#' Internal dispatch for fitting a single model + dataset
#'
#' @description
#' Called by [analyse.mb_model()] once the data have been validated and the
#' model has been compiled. Backend packages (`smbr2`, `jmbr`) register
#' methods for each engine.
#'
#' End users should call [analyse()], not `analyse1()` directly.
#'
#' @param model The mb_model to analyse.
#' @param data A validated data frame.
#' @param loaded The compiled / loaded model, as returned by [load_model()].
#' @inheritParams params
#' @param ... Additional arguments passed to the engine-specific estimation
#'   function.
#' @return An `mb_analysis` object.
#' @keywords internal
#' @export
analyse1 <- function(
  model,
  data,
  loaded,
  nchains,
  niters,
  nthin,
  quiet,
  glance,
  parallel,
  seed,
  niters_warmup,
  ...
) {
  UseMethod("analyse1")
}

analyse_data <- function(
  data,
  name = NULL,
  x,
  loaded,
  nchains,
  niters,
  nthin,
  parallel,
  quiet,
  glance,
  seed,
  niters_warmup,
  ...
) {
  check_no_sf(data)
  if (!is.null(name) & glance) {
    cat("Data:", name, "\n")
  }
  analyse1(
    x,
    data,
    loaded = loaded,
    nchains = nchains,
    niters = niters,
    nthin = nthin,
    parallel = parallel,
    quiet = quiet,
    glance = glance,
    seed = seed,
    niters_warmup = niters_warmup,
    ...
  )
}


analyse_model <- function(
  x,
  name = NULL,
  data,
  parallel,
  nchains,
  niters,
  nthin,
  quiet,
  glance,
  beep,
  stan_engine,
  ...
) {
  if (!is.null(name) & glance) {
    cat("Model:", name, "\n")
  }
  analyse(
    x,
    data = data,
    parallel = parallel,
    nchains = nchains,
    niters = niters,
    nthin = nthin,
    quiet = quiet,
    glance = glance,
    beep = beep,
    stan_engine = stan_engine,
    ...
  )
}

#' Analyse from Character Code
#'
#' A convenience that builds the model and fits it in one call.
#'
#' Only `select_data` is forwarded to [model()]. If you need to set
#' `new_expr`, `random_effects`, `new_expr_vec`, or `gen_inits`, build the
#' model with [model()] directly and pass it to [analyse()].
#'
#' @param x A character string of Stan or JAGS model code.
#' @param data A data frame.
#' @param select_data A named list specifying columns to select with their
#'   classes, values, transforms, and scaling options. Passed to [model()].
#' @inheritParams params
#' @param ... Additional arguments passed to [analyse()].
#' @return An `mb_analysis` or `mb_meta_analysis`. See [analyse()] for details.
#' @seealso [analyse()] for full argument documentation and engine details.
#' @export
analyse.character <- function(
  x,
  data,
  select_data = list(),
  nchains = getOption("mb.nchains", 3L),
  niters = getOption("mb.niters", 1000L),
  nthin = getOption("mb.nthin", 1L),
  parallel = getOption("mb.parallel", FALSE),
  quiet = getOption("mb.quiet", TRUE),
  glance = getOption("mb.glance", TRUE),
  beep = getOption("mb.beep", TRUE),
  seed = sample.int(.Machine$integer.max, 1),
  stan_engine = getOption("mb.stan_engine", character(0)),
  niters_warmup = niters,
  ...
) {
  x <- model(x, select_data = select_data)
  analyse(
    x,
    data = data,
    parallel = parallel,
    nchains = nchains,
    niters = niters,
    nthin = nthin,
    quiet = quiet,
    glance = glance,
    beep = beep,
    seed = seed,
    stan_engine = stan_engine,
    niters_warmup = niters_warmup,
    ...
  )
}

#' @rdname analyse
#' @export
analyse.mb_model <- function(
  x,
  data,
  nchains = getOption("mb.nchains", 3L),
  niters = getOption("mb.niters", 1000L),
  nthin = getOption("mb.thin", NULL),
  parallel = getOption("mb.parallel", FALSE),
  quiet = getOption("mb.quiet", TRUE),
  glance = getOption("mb.glance", TRUE),
  beep = getOption("mb.beep", TRUE),
  seed = sample.int(.Machine$integer.max, 1),
  stan_engine = getOption("mb.stan_engine", character(0)),
  niters_warmup = niters,
  ...
) {
  chk_flag(beep)
  if (beep) {
    on.exit(beepr::beep())
  }

  if (is.data.frame(data)) {
    chk_data(data)
  } else if (is.list(data)) {
    lapply(data, chk_data)
  } else {
    err("data must be a data.frame or a list of data.frames", tidy = FALSE)
  }

  chk_whole_number(nchains)
  chk_range(nchains, c(2L, 10L))
  chk_whole_number(niters)
  chk_range(niters, c(10L, 100000L))
  if (!is.null(nthin)) {
    chk_whole_number(nthin)
    chk_range(nthin, c(1L, 10000L))
  }

  chk_flag(parallel)
  chk_flag(quiet)
  chk_flag(glance)
  chk_whole_number(seed)
  chk_gt(seed, 0L)
  chk_character(stan_engine)
  chk_whole_number(niters_warmup)
  chk_range(niters_warmup, c(10L, 100000L))

  if (is.null(nthin)) {
    nthin <- nthin(x)
  }

  if (identical(stan_engine, "cmdstan-mcmc")) {
    class(x) <- c("cmdstan_model", "cmdstan_mcmc_model", class(x))
  } else if (identical(stan_engine, "cmdstan-pathfinder")) {
    class(x) <- c("cmdstan_model", "cmdstan_pathfinder_model", class(x))
  } else if (identical(stan_engine, "cmdstan-optimize")) {
    class(x) <- c("cmdstan_model", "cmdstan_optimize_model", class(x))
  } else if (identical(stan_engine, "cmdstan-laplace")) {
    class(x) <- c("cmdstan_model", "cmdstan_laplace_model", class(x))
  } else if (identical(stan_engine, "cmdstan-variational")) {
    class(x) <- c("cmdstan_model", "cmdstan_variational_model", class(x))
  }

  loaded <- load_model(x, quiet)

  if (is.data.frame(data)) {
    return(analyse_data(
      data = data,
      x = x,
      loaded = loaded,
      nchains = nchains,
      niters = niters,
      nthin = nthin,
      parallel = parallel,
      quiet = quiet,
      glance = glance,
      seed = seed,
      niters_warmup = niters_warmup,
      ...
    ))
  }

  names <- names(data)
  if (is.null(names)) {
    names(data) <- seq_along(data)
  }

  analyses <- purrr::imap(
    data,
    analyse_data,
    x = x,
    loaded = loaded,
    nchains = nchains,
    niters = niters,
    nthin = nthin,
    parallel = parallel,
    quiet = quiet,
    glance = glance,
    seed = seed,
    stan_engine = stan_engine,
    niters_warmup = niters_warmup,
    ...
  )

  names(data) <- names

  class(analyses) <- "mb_meta_analysis"
  analyses
}

#' Analyse Multiple Models
#'
#' Fits each model in an `mb_models` list against the same data, returning
#' an `mb_analyses` (or `mb_meta_analyses` if `data` is a list of data frames).
#'
#' @param x An `mb_models` list.
#' @param data A data frame, or a named list of data frames for meta-analysis.
#' @inheritParams params
#' @param ... Additional arguments passed to [analyse()].
#' @return An `mb_analyses` (single data frame) or `mb_meta_analyses` (list of
#'   data frames).
#' @seealso [analyse()] for full argument documentation and engine details.
#' @export
analyse.mb_models <- function(
  x,
  data,
  nchains = getOption("mb.nchains", 3L),
  niters = getOption("mb.niters", 1000L),
  nthin = getOption("mb.thin", NULL),
  parallel = getOption("mb.parallel", FALSE),
  quiet = getOption("mb.quiet", TRUE),
  glance = getOption("mb.glance", TRUE),
  beep = getOption("mb.beep", TRUE),
  seed = sample.int(.Machine$integer.max, 1),
  stan_engine = getOption("mb.stan_engine", character(0)),
  niters_warmup = niters,
  ...
) {
  chk_flag(beep)
  if (beep) {
    on.exit(beepr::beep())
  }

  names <- names(x)
  if (is.null(names)) {
    names(x) <- seq_along(x)
  }

  analyses <- purrr::imap(
    x,
    analyse_model,
    data = data,
    nchains = nchains,
    niters = niters,
    nthin = nthin,
    parallel = parallel,
    quiet = quiet,
    glance = glance,
    beep = FALSE,
    seed = seed,
    stan_engine = stan_engine,
    niters_warmup = niters_warmup,
    ...
  )

  if (is.data.frame(data)) {
    analyses <- as_mb_analyses(analyses, names)
    return(analyses)
  }
  analyses <- purrr::transpose(analyses)
  analyses <- purrr::map(analyses, as_mb_analyses, names)
  class(analyses) <- "mb_meta_analyses"
  analyses
}
